backend:
  replicaCount: 1
  image:
    repository: ghcr.io/gkestenberg/helm-2-deploy-backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
  resources: {}

frontend:
  replicaCount: 1
  image:
    repository: ghcr.io/gkestenberg/helm-2-deploy-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
  env:
    apiUrl: "http://backend:8000"
  resources: {}

ingress:
  enabled: false
  className: ""
  host: ""
